main: cn.wode490390.nukkit.rollbossbar.RollBossBar
name: "RollBossBar"
description: "Roll boss bar plugin for Nukkit"
author: "wode490390"
website: "http://wode490390.cn/"
version: "${pom.version}"
api: ["1.0.0"]
load: POSTWORLD
